#!/bin/bash

CUR_DIR=~/Documents/Tesi/inst-t
BIN=twisterd
#extip=$EXTIP
extip=127.0.0.1
pb=380
pb2=$(($pb+100))

if [ "$1" = "start" ]; then
    if [ -z "$2" ]; then
	echo -e "usage:\naLaunch start <node> [end-node]"
	exit 0
    fi
    
    if [ -z "$3" ]; then # start <node>
	echo "$0: creo il nodo $2"
	end_node=$2
    elif [ $(( $2 < $3 )) ]; then # start <node> [end-node]
	echo "$0: creo i $(( $3-$2+1 )) nodi"
	end_node=$3
    else
	echo -e "end-node must be greater than start node"
	exit 0
    fi
	rnodes=0
    for i in $(seq -f %02g $2 $end_node)
    do
	if [ -f $CUR_DIR/$i.pid ]; then
	    if [ ! -z "$( pgrep -F $CUR_DIR/$i.pid )" ]; then
	    echo "node $i is already running"
		rnodes=$((rnodes+1))
	    continue
	    fi
	fi
	if [ ! -d $CUR_DIR/acc-$i ]; then
	    mkdir -p $CUR_DIR/acc-$i
	fi
	# scrive su file il suo pid in modo da poter essere killato in automatico
	echo "./$BIN -datadir=$CUR_DIR/acc-$i -port=$pb$i -genproclimit=1 -daemon -rpcport=$pb2$i -rpcuser=user -rpcpassword=pwd -rpcallowip=127.0.0.1 -pid=$CUR_DIR/$i.pid"
	./$BIN -datadir=$CUR_DIR/acc-$i -port="$pb$i" -genproclimit=1 -daemon -rpcport="$pb2$i" -rpcuser=user -rpcpassword=pwd -rpcallowip=127.0.0.1 -pid=$CUR_DIR/$i.pid > /dev/null
    done
    echo -n "Starting servers"
    for i in $(seq $2 $(($end_node-$rnodes)))
    do
	echo -n "."
	sleep 1
	done
    echo -e "\nServers initialized.\n"
elif [ "$1" = "connect" ]; then
    if [ "$2" != "" ] && [ "$3" != "" ]; then
	if ! $0 cmd $2 addnode $extip:$pb$(printf %02g $3) onetry; then
	    echo "connection aborted"
	else
	    echo "connecting $2 to $3"
	fi
    else
	echo -e "usage:\n\t$0 connect <node1> <node2>"
    fi
elif [ "$1" = "cmd" ]; then
    if (($#<3)); then
	echo -e "usage:\n\t$0 cmd <node> <command> [params]\ntry command help on any node"
	exit 1
    fi
    node=$(printf %02g $2)
    if [ ! -f $CUR_DIR/$node.pid ]; then
	echo "node $node was never started"
	exit 1
    fi
    c_pid=$( cat $CUR_DIR/$node.pid )
    if [ -z "$( pgrep -F $CUR_DIR/$node.pid )" ]; then
	echo "node $node does not appear to be running"
	exit 1
    fi
    args=($@)
    params="${args[2]}"
    for i in $(seq 3 $#)
    do
	if [ ! -z "${args[$i]}" ]; then
		params=$params\ ${args[$i]}
	fi
    done
    echo "./$BIN -genproclimit=1 -rpcuser=user -rpcpassword=pwd -rpcallowip=127.0.0.1 -rpcport=$pb2$(printf %02g $2)"\ $params
    ./$BIN -genproclimit=1 -rpcuser=user -rpcpassword=pwd -rpcallowip=127.0.0.1 -rpcport=$pb2$(printf %02g $2) $params
elif [ "$1" = "pause" ]; then
    if [ -z "$2" ]; then
	echo -e "usage:\n\t$0 pause <node> [end-node]"
	exit 0
    fi
    if [ -z "$3" ]; then
	end_node=$2
    else
	end_node=$3
    fi
    echo "$0: metto in pausa $((end_node-$2+1)) nodo/i"
    for i in $(seq -f %02g $2 $end_node)
    do
	if [ ! -f $CUR_DIR/$i.pid ]; then
	    echo "node $i was never started"
	    continue
	fi
	c_pid=$( cat $CUR_DIR/$i.pid )
	if [ -z "$( pgrep -F $CUR_DIR/$i.pid )" ]; then
	    echo "node $i does not appear to be running"
	    continue
	fi
	echo "./$BIN -rpcuser=user -rpcpassword=pwd -rpcallowip=127.0.0.1 -rpcport=2\
76$i stop"
	./$BIN -rpcuser=user -rpcpassword=pwd -rpcallowip=127.0.0.1 -rpcport=$pb2$i stop
    done
elif [ "$1" = "delete" ]; then
    if [ -z "$2" ]; then
	echo -e "usage:\n\t$0 delete <node> [end-node]"
	exit 0
    fi
    if [ -z "$3" ]; then
	end_node=$2
    else
	end_node=$3
    fi
    echo "will kill all nodes ranging $2 to $end_node"
    for i in $(seq -f %02g $2 $end_node)
    do
	if [ ! -f $CUR_DIR/$i.pid ]; then
	    echo "node $i was never started"
	    continue
	fi
	c_pid=$( cat $CUR_DIR/$i.pid )
	if [ -z "$( pgrep -F $CUR_DIR/$i.pid )" ]; then
	    echo "node $i (PID $c_pid) does not appear to be running"
	    continue
	fi
	echo "killing node $i (PID: $c_pid)"
	kill -KILL $c_pid
    done
    for i in $(seq -f %02g $2 $end_node)
    do
	if [ ! -d "$CUR_DIR/acc-$i" ]; then
	    echo "node $i does not appear to have a workdir"
	    continue
	fi
	cd $CUR_DIR/acc-$i
	ls | grep -v debug.log | grep -v html | xargs rm -rf
	echo "file cancellati per il nodo $i"
    done
elif [ "$1" = "rhtml" ]; then
    if [ "$2" == "" ]; then
	echo -e "Usage:\n\t$0 rhtml <node> [end-node]"
	exit 0
    elif [ "$2" != "" ] && [ "$3" != "" ]; then
	end_node=$3
    else
	end_node=$2
    fi
    for i in $(seq -f %02g $2 $end_node)
    do
	if [ ! -d ./html ]; then
	    echo "html directory not found, change directory to the parent of the html directory"
	    exit 0
	fi
	if [ -d $CUR_DIR/acc-$i/html ]; then
	    mv $CUR_DIR/acc-$i/html $CUR_DIR/html-backup-$i-$(date +%s)
	fi
	cp -R ./html $CUR_DIR/acc-$i/html
	echo "./html copyed to $CUR_DIR/acc-$i/"
    done
elif [ "$1" = "lboot" ]; then
    if [ "$2" == "" ]; then
	echo -e "Usage:\n\t$0 lboot <node> [end-node]"
	exit 0
    fi    
    if [ "$2" != "" ] && [ "$3" != "" ]; then
	end_node=$3
    else
	end_node=$2
    fi
    for i in $(seq -f %02g $2 $end_node)
    do
	if [ ! -f ./bootstrap.dat ]; then
	    echo "bootstrap.dat not found it should be in the current dir"
	    exit 0
	fi
	cp ./bootstrap.dat $CUR_DIR/acc-$i/bootstrap.dat
	echo "./bootstrap.dat copied to $CUR_DIR/acc-$i/"
	cp ./twisterwallet.dat $CUR_DIR/acc-$i/twisterwallet.dat
	echo "./twisterwallet.dat copied $CUR_DIR/acc-$i/"
    done
else
    echo -e "usage:\n\t$0 start <node> [end-node]\n\t$0 delete <node> [end-node]\n\t$0 pause <node> [end-node]\n\t$0 connect <node1> <node2>\n\t$0 cmd <node> <command> [params]\n\t$0 rhtml <node> [end-node]\n\t$0 lboot <node> [end-node]"
fi
